### ISSUE TITLE
Problem with importing iterm2 color preset.

### ISSUE THREAD

**Issue by konekoya** [carloscuesta/materialshell#11]
Hello @carloscuesta

- **OS**: macOS Sierra
- **Shell Emulator**: zsh

I was following your shell color [importing instruction](https://github.com/carloscuesta/materialshell#os-x),  but when I was importing the color preset from iTerm2 I got an error message saying "The selected file could not be read or did not contain a valid color scheme." So I guess I might have downloaded a wrong file?  I downloaded the preset as a raw file from [here](https://raw.githubusercontent.com/carloscuesta/materialshell/master/osx/iterm/materialshell-dark.itermcolors).
Thanks for this beautiful theme :)

**Comment by carloscuesta** [comment]
Hey @konekoya

Hmmmm, seems like a weird issue, I have downloaded the file and works fine!

Did you saved the file with the `.itermcolors` extension ?

Try this file: [materialshell-dark.itermcolors.zip](https://github.com/carloscuesta/materialshell/files/679540/materialshell-dark.itermcolors.zip)

**Comment by konekoya** [comment]
@carloscuesta OOPS! I'm really sorry, it's just I forgot the file extension. Now the theme works perfectly! Thank you for this great shell color theme!

**Comment by liannivin** [comment]
Thanks everyone! `.itermcolors` extension works.
