### ISSUE TITLE
Green color is too yellowish

### ISSUE THREAD

**Issue by kevinresol** [carloscuesta/materialshell#15]
Thanks for the great theme! But I found the green color is too yellowish. I think it would be better to choose a "greener" green.

<img width="423" alt="screen shot 2017-04-07 at 9 38 38 am" src="https://cloud.githubusercontent.com/assets/1103788/24781999/099f5776-1b76-11e7-8ef0-5e0179173e40.png">

As seen in the image above, the `[OK]`'s and the last summary line is actually green (but it looks yellow), while the header (`reverse`) is yellow (but it looks orange)

**Comment by carloscuesta** [comment]
Color display may change depending on the screen profile color used. I don't think that the green tone needs a change, in fact this is the first request for that. By the way, you can change the green color at your terminal preferences. :+1:
