### ISSUE TITLE
Same background and foreground color for git branch

### ISSUE THREAD

**Issue by unikapps** [carloscuesta/materialshell#18]
I used the theme with Cmder, everything looks ok except when i first CD to a git repository i can't see the branch name, because the background and foreground are the same

![cmder](https://cloud.githubusercontent.com/assets/1418027/25569220/b4ed3f52-2e0a-11e7-99d1-cc51977dbcda.png)

**Comment by carloscuesta** [comment]
What .zsh-theme are you using?
