### ISSUE TITLE
Terminal theme black color issue

### ISSUE THREAD

**Issue by Dids** [carloscuesta/materialshell#19]
Hello @carloscuesta

- **OS**: macOS Sierra 10.12.4
- **Shell Emulator**: Terminal

With the ocean materialshell theme for Terminal, there's black text that's hard to distinguish from the background. Is this on purpose, did I manage to break it or is it a bug?

![Terminal Screenshot](https://www.dropbox.com/s/7m9kj7k3n7q2wfp/Screenshot%202017-05-08%2009.56.17.png?dl=1)

**EDIT**: Looks like it's the "bolded text" option in the Terminal theme that's defaulting to black.

**Comment by carloscuesta** [comment]
Switched to white, thanks @Dids 👍
