### ISSUE TITLE
Fails while trying to use with Antigen

### ISSUE THREAD

**Issue by coderxx** [carloscuesta/materialshell#20]
Hello @carloscuesta

- **Raspberry Pi running Debian Jesse Lite**:
- **ZSH**:

When I try installing the theme using Antigen [https://github.com/zsh-users/antigen](url), the installation fails with error: 

`Installing carloscuesta/materialshell@master... Done. Took 4s.'

After that - 

`Antigen: Failed to load theme.`

Error log produces this - 

`Cloning into '/home/pi/.antigen/bundles/carloscuesta/materialshell'...`

Nothing after.

The command I used was 
`antigen theme carloscuesta/materialshell themes/materialshell`

**Comment by carloscuesta** [comment]
Hi @coderxx this is strange, I don't use antigen for managing zsh packages, will take a look 🤔

**Comment by rekjresz** [comment]
@coderxx 
to load the theme i use this code on my .zshrc file :
`antigen theme carloscuesta/materialshell zsh/materialshell`
