### ISSUE TITLE
Font used?

### ISSUE THREAD

**Issue by flomk** [carloscuesta/materialshell#21]
Hello @carloscuesta

- **OS**: OS X El Capitan
- **Shell Emulator**: iTerm2

I would just like to know what font is being used in the screenshots. Thanks

**Comment by carloscuesta** [comment]
The font used at the screenshots is **Consolas**.  #3

**Comment by kolmogorov42** [comment]
BTW, what's your fallback font for icons? Consolas on Windows looks good, but doesn't seem to have a lot of glyphs outside text.

**Comment by carloscuesta** [comment]
As far as I know, I do not use any fallback font @kolmogorov42. Probably its due to Windows
