### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by knightseal** [carloscuesta/materialshell#28]
Hello @carloscuesta

- **OS**: 10.13.4 
- **Shell Emulator**: zsh

![image](https://user-images.githubusercontent.com/2109057/39390475-846ce104-4ac7-11e8-9650-fe53e54691fa.png)

**Comment by mtford90** [comment]
Exact same error on 10.13.3

**Comment by carloscuesta** [comment]
I’ll take a look on that

**Comment by cammace** [comment]
for me, changing the theme definition to:
```
antigen theme carloscuesta/materialshell materialshell
```

resolved the issue. the `.zsh-theme` file is in the root directory, not a folder called `zsh`.

**Comment by carloscuesta** [comment]
That makes a lot of sense @cammace
