### ISSUE TITLE
Hi, could you please tell me which font you're using now? 

### ISSUE THREAD

**Issue by vincent178** [carloscuesta/materialshell#3]
Thanks

**Comment by carloscuesta** [comment]
Hello! 

The font that I'm using for the shell is [Consolas](https://en.wikipedia.org/wiki/Consolas) at 13 pt.

![consolas](https://cloud.githubusercontent.com/assets/7629661/13903939/9274d20c-ee8f-11e5-824b-7b15eb6c1fcf.png)

**Comment by vincent178** [comment]
Thank you so much!
