### ISSUE TITLE
Working path not showing up

### ISSUE THREAD

**Issue by raksdewji** [carloscuesta/materialshell#31]
Hello @carloscuesta

- **OS**: Arch Linux
- **Shell Emulator**: Konsole

I have installed antigen and used the plugin to add this materialshell and a couple other plugins. All has gone well except on my command prompt it doesn't show the current working path. 

Ex. https://i.imgur.com/8umJYL3.png

**Comment by raksdewji** [comment]
solution: added the theme manually and not using a plugin manager

**Comment by heyyong** [comment]
@carloscuesta is there some plan to fix it so i can use with plugin manager? thx.

**Comment by carloscuesta** [comment]
Not really since I can’t reproduce it @EdenCao

**Comment by heyyong** [comment]
@carloscuesta 
**OS**: macOS Mojave v10.14.4
**Terminal**: iTerm2 v3.2.9
**zsh package manager**: antigen

it just works when i change local variable _current_dir to a function,but i do not konw why.
```
// materialshell/materialshell.sh
// change _current_dir to function invoking
PROMPT='$(_user_host)$(_current_dir)$(git_prompt_info)
...
// change to function declaration
function _current_dir() {
  echo "%{$green%}%0~%{$reset_color%}"
}
```
