### ISSUE TITLE
Local variables don't work with Antigen

### ISSUE THREAD

**Issue by mtslzr** [carloscuesta/materialshell#32]
- macOS 10.14.2
- Hyper 2.0.0

When installing materialshell via Antigen, local variables are not read. This causes `_current_dir` to not work, and the prompt won't show the PWD. Removing `local` fixes the issue (found in https://github.com/zsh-users/antigen/issues/117, being tracked in https://github.com/zsh-users/antigen/issues/122).

That said, not sure if you want to change materialshell (or wait from some sort of change/fix from Antigen/oh-my-zsh), but you should at least update the documentation to note the issue.

**Comment by carloscuesta** [comment]
This is related with #31

**Comment by mtslzr** [comment]
Ah, yeah. Looks like he just worked around it. Which is fine, but I think it warrants a mention in the README then, maybe.
