### ISSUE TITLE
Tmux theme

### ISSUE THREAD

**Issue by oldgalileo** [carloscuesta/materialshell#6]
Hello @carloscuesta! As someone who is inept at selecting colors but a fan of your selections, it would be awesome to have the theme extend into tmux.
- **OS**: Mac OS X
- **Shell Emulator**: iTerm2

**Comment by ghost** [comment]
I think there's another issue who request the theme to be extend into iTerm.

Can you please send a PR? (If you can)

**Comment by carloscuesta** [comment]
Hello @HowardStark feel free to submit a pull request with the integration to Tmux.

I will take a look to your request, but any help is appreciated!

Thanks for submitting an issue :+1:
