### ISSUE TITLE
Create a light materialshell theme

### ISSUE THREAD

**Issue by carloscuesta** [carloscuesta/materialshell#9]
Create a light color version of materialshell.
- [ ] Terminal & iTerm version.
- [ ] Update docs

**Comment by ghost** [comment]
What do you mean by "docs"?

**Comment by ghost** [comment]
The wiki or `README.md`?

**Comment by carloscuesta** [comment]
Updating the README with screenshots of the new theme and probably the header gif.

**Comment by ghost** [comment]
Let me do you a favor bro :)

**Comment by ghost** [comment]
I've checked the issue and you probably need another guy to reply to that kinda issue, I probably can help you with that.

But the shell, I don't think I can since I'm actually a front-end developer😂
